### ISSUE TITLE
Receive: Do Checklist

### ISSUE THREAD

**Issue by DanGould** [Kixunil/payjoin#26]
# [BIP 78 Receiver Checklist](https://github.com/bitcoin/bips/blob/master/bip-0078.mediawiki#receivers-original-psbt-checklist)

> ===Receiver's original PSBT checklist===
> 
> The receiver needs to do some check on the original PSBT before proceeding:
> 

## 1

> *  Non-interactive receivers (like a [offline] payment processor) need to check that the original PSBT is broadcastable. <code>*</code>

Check by iterating through [the rust-miniscript interpreter `iter()`](https://docs.rs/miniscript/latest/miniscript/interpreter/struct.Interpreter.html#method.iter).

## 2

> * If the sender included inputs in the original PSBT owned by the receiver, the receiver must either return error <code>original-psbt-rejected</code> or make sure they do not sign those inputs in the payjoin proposal.

Shouldn't a broadcast check just be used for both 1 & 2 since we can embed rust-miniscript interpreter? If not, pass available descriptors to this check. Maybe this is just to prevent reentrant payjoin.

## 3

> * If the sender's inputs are all from the same scriptPubKey type, the receiver must match the same type. If the receiver can't match the type, they must return error <code>unavailable</code>.

This check is the most straightforward of the bunch. Ask for an available output descriptor with the same scriptPubKey. This check should really be done during the actual coin selection, after the others imo

## 4

> * Make sure that the inputs included in the original transaction have never been seen before.
>   * This prevent [probing attacks](https://github.com/bitcoin/bips/blob/master/bip-0078.mediawiki#on-the-receiver-side-utxo-probing-attack).
>   * This prevent reentrant payjoin, where a sender attempts to use payjoin transaction as a new original transaction for a new payjoin.
> 
> <code>*</code>: Interactive receivers are not required to validate the original PSBT because they are not exposed to probing attacks [since they can broadcast the original transaction]

Not sure what the best way to do this check would be. Maybe ask for hashmap of all the before-seen inputs? I feel like I'm thinking about this part as library code in the wrong way.

# Arch
The stub model is a type-based state machine. 
## Past attempts

Lesson 1: don't assume sync/async arch. This is rust-payjoin, not payjoin-dev-kit https://github.com/Kixunil/payjoin/pull/19 

Lesson 2: don't complicate state. Perhaps bitflags can keep track of what's been validated instead. https://github.com/Kixunil/payjoin/pull/23. Do checks in consumer code and call `assume` function after. Even though that seems like a danger to me.

**Comment by Kixunil** [comment]
All these need to be handled by the consumer code. This library only provides processing of the protocol and correct construction of PSBT.

**Comment by Kixunil** [comment]
Currently the design is to take in request and process it as series of steps where the consumer performs these checks guided by the library. I don't think we can implement those ourselves.

1. the only way to correctly test broadcastability is to call into bitcoind, our code can't do that.
2. we don't know which inputs belong to the receiver and there are multiple ways to check it (what if the receiver has multiple xpubs?) Best to iterate over those and ask receiver to check each.
3. Honestly, I think this check shouldn't exist at all (mixed spends are not actually a problem). Anyway, rather than requiring the consumer to supply an iterator of supported types, we just make type available and then error if the consumer attempts to supply a wrong input.
4. This needs some kind of database, our library must not dictate how the data is stored.
